config/routes.rb
Rails.application.routes.draw do
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'recipes/index'
  root 'recipes#index'

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/about" => "about#manifesto", as: "about"
  get "/construction" => "about#construction", as: "soon"

  get "/profile" => "users#show", as: "profile"

  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

    resources :users do

      resources :cook_books

      resources :menus do
        resources :courses_menus
      end

    end

end

app/models/courses_menu.rb
class CoursesMenu < ActiveRecord::Base
  belongs_to :menu
  has_and_belongs_to_many :recipes, dependent: :destroy
end

app/controllers/courses_menus_controller.rb
class CoursesMenusController < ApplicationController
  before_action :set_courses_menu, only: [:show, :edit, :update, :destroy]

  # GET /courses_menus
  # GET /courses_menus.json
  def index
    @courses_menus = CoursesMenu.all
  end

  # GET /courses_menus/1
  # GET /courses_menus/1.json
  def show
  end

  # GET /courses_menus/new
  def new
    @courses_menu = CoursesMenu.new
  end

  # GET /courses_menus/1/edit
  def edit
  end

  # POST /courses_menus
  # POST /courses_menus.json
  def create
    @courses_menu = CoursesMenu.new(courses_menu_params)

    respond_to do |format|
      if @courses_menu.save
        format.html { redirect_to @courses_menu, notice: 'Courses menu was successfully created.' }
        format.json { render :show, status: :created, location: @courses_menu }
      else
        format.html { render :new }
        format.json { render json: @courses_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses_menus/1
  # PATCH/PUT /courses_menus/1.json
  def update
    respond_to do |format|
      if @courses_menu.update(courses_menu_params)
        format.html { redirect_to @courses_menu, notice: 'Courses menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @courses_menu }
      else
        format.html { render :edit }
        format.json { render json: @courses_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses_menus/1
  # DELETE /courses_menus/1.json
  def destroy
    @courses_menu.destroy
    respond_to do |format|
      format.html { redirect_to courses_menus_url, notice: 'Courses menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courses_menu
      @courses_menu = CoursesMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def courses_menu_params
      params.require(:courses_menu).permit(:course_name, :day, :menu_id)
    end
end

app/helpers/courses_menus_helper.rb
module CoursesMenusHelper
end

app/views/courses_menus/_form.html.erb
<%= form_for(@courses_menu) do |f| %>
  <% if @courses_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@courses_menu.errors.count, "error") %> prohibited this courses_menu from being saved:</h2>

      <ul>
      <% @courses_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_name %><br>
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :menu_id %><br>
    <%= f.text_field :menu_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses_menus/edit.html.erb
<h1>Editing Courses Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @courses_menu %> |
<%= link_to 'Back', courses_menus_path %>

app/views/courses_menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses Menus</h1>

<table>
  <thead>
    <tr>
      <th>Course name</th>
      <th>Day</th>
      <th>Menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses_menus.each do |courses_menu| %>
      <tr>
        <td><%= courses_menu.course_name %></td>
        <td><%= courses_menu.day %></td>
        <td><%= courses_menu.menu %></td>
        <td><%= link_to 'Show', courses_menu %></td>
        <td><%= link_to 'Edit', edit_courses_menu_path(courses_menu) %></td>
        <td><%= link_to 'Destroy', courses_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Courses menu', new_courses_menu_path %>

app/views/courses_menus/new.html.erb
<h1>New Courses Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_menus_path %>

app/views/courses_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @courses_menu.course_name %>
</p>

<p>
  <strong>Day:</strong>
  <%= @courses_menu.day %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @courses_menu.menu %>
</p>

<%= link_to 'Edit', edit_courses_menu_path(@courses_menu) %> |
<%= link_to 'Back', courses_menus_path %>