config/routes.rb
Rails.application.routes.draw do
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'recipes/index'
  root 'recipes#index'

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/about" => "about#manifesto", as: "about"
  get "/construction" => "about#construction", as: "soon"

  get "/profile" => "users#show", as: "profile"

  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

    resources :users do

      resources :cook_books

      resources :menus do
        resources :courses_menus
      end

    end

end

app/models/cook_book.rb
class CookBook < ActiveRecord::Base
  belongs_to :user
  has_many :recipes, dependent: :destroy
end

app/controllers/cook_books_controller.rb
class CookBooksController < ApplicationController
  before_action :set_cook_book, only: [:show, :edit, :update, :destroy]

  # GET /cook_books
  # GET /cook_books.json
  def index
    @cook_books = CookBook.all
  end

  # GET /cook_books/1
  # GET /cook_books/1.json
  def show
  end

  # GET /cook_books/new
  def new
    @cook_book = CookBook.new
  end

  # GET /cook_books/1/edit
  def edit
  end

  # POST /cook_books
  # POST /cook_books.json
  def create
    @cook_book = CookBook.new(cook_book_params)

    respond_to do |format|
      if @cook_book.save
        format.html { redirect_to @cook_book, notice: 'Cook book was successfully created.' }
        format.json { render :show, status: :created, location: @cook_book }
      else
        format.html { render :new }
        format.json { render json: @cook_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cook_books/1
  # PATCH/PUT /cook_books/1.json
  def update
    respond_to do |format|
      if @cook_book.update(cook_book_params)
        format.html { redirect_to @cook_book, notice: 'Cook book was successfully updated.' }
        format.json { render :show, status: :ok, location: @cook_book }
      else
        format.html { render :edit }
        format.json { render json: @cook_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cook_books/1
  # DELETE /cook_books/1.json
  def destroy
    @cook_book.destroy
    respond_to do |format|
      format.html { redirect_to cook_books_url, notice: 'Cook book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cook_book
      @cook_book = CookBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cook_book_params
      params.require(:cook_book).permit(:name, :description, :user_id)
    end
end

app/helpers/cook_books_helper.rb
module CookBooksHelper
end

app/views/cook_books/_form.html.erb
<%= form_for(@cook_book) do |f| %>
  <% if @cook_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cook_book.errors.count, "error") %> prohibited this cook_book from being saved:</h2>

      <ul>
      <% @cook_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cook_books/edit.html.erb
<h1>Editing Cook Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @cook_book %> |
<%= link_to 'Back', cook_books_path %>

app/views/cook_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cook Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cook_books.each do |cook_book| %>
      <tr>
        <td><%= cook_book.name %></td>
        <td><%= cook_book.description %></td>
        <td><%= cook_book.user %></td>
        <td><%= link_to 'Show', cook_book %></td>
        <td><%= link_to 'Edit', edit_cook_book_path(cook_book) %></td>
        <td><%= link_to 'Destroy', cook_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cook book', new_cook_book_path %>

app/views/cook_books/new.html.erb
<h1>New Cook Book</h1>

<%= render 'form' %>

<%= link_to 'Back', cook_books_path %>

app/views/cook_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cook_book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cook_book.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @cook_book.user %>
</p>

<%= link_to 'Edit', edit_cook_book_path(@cook_book) %> |
<%= link_to 'Back', cook_books_path %>